# Copyright 2019-2023 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: covector version or publish v1

on:
  push:
    branches:
      - 1.x
      - v1/msrv-check

jobs:
  msrv-list:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: core
            flags: '--manifest-path=./Cargo.toml --features tracing,compression,wry,linux-protocol-headers,isolation,custom-protocol,api-all,cli,updater,system-tray,windows7-compat,http-multipart,test'
          - name: bundler
            flags: '--manifest-path=./tooling/bundler/Cargo.toml'
            toolchain: '1.71.0'
          - name: cli
            flags: '--manifest-path=./tooling/cli/Cargo.toml'
            toolchain: '1.71.0'

        platform:
          - {
              target: x86_64-pc-windows-msvc,
              os: windows-latest,
              toolchain: '1.61.0'
            }
          - {
              target: x86_64-unknown-linux-gnu,
              os: ubuntu-22.04,
              toolchain: '1.60.0'
            }
          - {
              target: x86_64-apple-darwin,
              os: macos-13,
              toolchain: '1.60.0'
            }
    steps:
      - uses: actions/checkout@v4

      - name: install rust stable for MSRV check
        uses: dtolnay/rust-toolchain@stable

      - name: install Linux dependencies
        if: contains(matrix.platform.target, 'unknown-linux')
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 libayatana-appindicator3-dev

      - uses: Swatinem/rust-cache@v2

      - name: regen lockfile using cargo >=1.84
        env:
          CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: fallback
        run: |
          rm Cargo.lock
          rm tooling/bundler/Cargo.lock
          rm tooling/cli/Cargo.lock
          cargo generate-lockfile
          cd tooling/bundler
          cargo generate-lockfile
          cd ../cli
          cargo generate-lockfile

      - name: Downgrade crates with MSRV conflict (core)
        if: ${{ matrix.project.name == 'core' }}
        env:
          CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: fallback
        # The --precise flag can only be used once per invocation.
        # at least h2 and syn don't need the precise flag here with cargo 1.84
        run: |
          cargo update -p backtrace --precise 0.3.68
          cargo update -p hyper --precise 0.14.27
          cargo update -p h2 --precise 0.3.20
          cargo update -p serde_json --precise 1.0.97
          cargo update -p arboard --precise 3.2.1
          cargo update -p tempfile --precise 3.6.0
          cargo update -p regex --precise 1.9.6
          cargo update -p tar --precise 0.4.39
          cargo update -p serde --precise 1.0.210
          cargo update -p syn:2 --precise 2.0.67
          cargo update -p globset --precise 0.4.13
          cargo update -p xml-rs --precise 0.8.20
          cargo update -p derive_more --precise 0.99.17
          cargo update -p thread_local --precise 1.1.7
          cargo update -p mac-notification-sys --precise 0.6.1
          cargo update -p ignore --precise 0.4.18
          cargo update -p tree_magic_mini --precise 3.0.3
          cargo update -p native-tls --precise 0.2.11

      - name: install rust ${{ matrix.project.toolchain || matrix.platform.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.project.toolchain || matrix.platform.toolchain }}
          target: ${{ matrix.platform.target }}

      - name: test build
        run: cargo check --target ${{ matrix.platform.target }} ${{ matrix.project.flags }}

  run-integration-tests:
    runs-on: ${{ matrix.platform }}
    needs: msrv-list
    if: github.ref == 'refs/heads/1.x'

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, macos-13, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install stable
        uses: dtolnay/rust-toolchain@stable
      - name: install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 webkit2gtk-4.1 libayatana-appindicator3-dev libfuse2

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: |
            core -> ../target
            tooling/cli
            core/tests/app-updater/tests/fixtures/tauri-v1
            core/tests/app-updater/tests/fixtures/tauri-v2/src-tauri

      - name: build CLI
        run: cargo build --manifest-path ./tooling/cli/Cargo.toml

      - name: run integration tests
        run: cargo test --test '*' -- --ignored

      - name: run CLI tests
        timeout-minutes: 30
        run: |
          cd ./tooling/cli/node
          yarn
          yarn build
          yarn test

  version-or-publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 65
    permissions:
      actions: write # required for workflow_dispatch
      contents: write # required to create new releases
      pull-requests: write # required to open version update pr
    outputs:
      change: ${{ steps.covector.outputs.change }}
      commandRan: ${{ steps.covector.outputs.commandRan }}
      successfulPublish: ${{ steps.covector.outputs.successfulPublish }}
    needs:
      - run-integration-tests

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: yarn
          cache-dependency-path: tooling/*/yarn.lock

      - name: cargo login
        run: cargo login ${{ secrets.ORG_CRATES_IO_TOKEN }}
      - name: git config
        run: |
          git config --global user.name "${{ github.event.pusher.name }}"
          git config --global user.email "${{ github.event.pusher.email }}"

      - name: covector version or publish (publish when no change files present)
        uses: jbolda/covector/packages/action@covector-v0
        id: covector
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_NPM_TOKEN }}
          CARGO_AUDIT_OPTIONS: ${{ secrets.CARGO_AUDIT_OPTIONS }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: 'version-or-publish'
          createRelease: true
          recognizeContributors: true

      - name: Create Pull Request With Versions Bumped
        if: steps.covector.outputs.commandRan == 'version'
        uses: tauri-apps/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/version-updates-v1
          title: Apply Version Updates From Current Changes (v1)
          commit-message: 'apply version updates'
          labels: 'version updates'
          body: ${{ steps.covector.outputs.change }}

      - name: Trigger doc update
        if: |
          steps.covector.outputs.successfulPublish == 'true' &&
          steps.covector.outputs.packagesPublished != ''
        run: gh workflow run 18856068 -r v1 -R tauri-apps/tauri-docs
        env:
          GH_TOKEN: ${{ secrets.ORG_TAURI_BOT_PAT }}

      - name: Trigger `@tauri-apps/cli` publishing workflow
        if: |
          steps.covector.outputs.successfulPublish == 'true' &&
          contains(steps.covector.outputs.packagesPublished, '@tauri-apps/cli')
        run: gh workflow run 31554138 -r 1.x -f releaseId=${{ steps.covector.outputs['-tauri-apps-cli-releaseId'] }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger `tauri-cli` publishing workflow
        if: |
          steps.covector.outputs.successfulPublish == 'true' &&
          contains(steps.covector.outputs.packagesPublished, 'tauri-cli')
        run: gh workflow run 31554139 -r 1.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
